# Generated by Django 5.0.6 on 2024-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240722_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_field',
            field=models.CharField(blank=True, default='default_value', max_length=100),
        ),
    ]
